### ISSUE TITLE
Security Issue: Use of non CSPRNG for key generation

### ISSUE THREAD

**Issue by MiWCryptAnalytics** [davb5/pydiceware#1]
Hi!

I notice in diceware.py:21 you are using 
[random.choice(wordlist) for x in range(length)] as a source of randomness.

random.choice is not a cryptographically secure random number generator (CSPRNG), and so is not suitable for long term key generation (which diceware is providing). 

It means all previous diceware passphrases generated with this library are potentially weak, due to the low entropy of the default random number generator. It is recommended these be regenerated with a CSPRNG.

In python 3.6, the secrets.choice() gives you the most secure random number generation for that platform.
You can also do random.SystemRandom() to interface with the native /dev/urandom file, which is a CSPRNG.

secrets seems the preferred way moving forward, and gives you the desired choice() functionality.

**Comment by davebarkerxyz** [comment]
@MiWCryptAnalytics Thanks for your suggestion. I think `secrets` is out of the question as Python 3.6 usage isn't prevalent enough, however https://github.com/davb5/pydiceware/commit/e1510fb3beb776ad01bf6fe6b3415d1fd7959821 now makes use of SystemRandom. Cheers.

**Comment by MiWCryptAnalytics** [comment]
Hi @dav5, you have closed this without fixing the randomness security issue. e1510fb3beb776ad01bf6fe6b3415d1fd7959821 defaults it to five words in the function, it doesn't make use of the SystemRandom class?

**Comment by davebarkerxyz** [comment]
@MiWCryptAnalytics Sorry - my bad. I pushed it to a local server and neglected to push it to Github. It's up now as 44e9e06c7db64682340505754af0b69b99cae305
